// The 7 built-in StyleThemes (docs/11-motion-library.md "Uslublar").
// Colours start from the docs/08 tokens (bg #0B0F19, surface #131A2A, text
// #E6EAF2, muted #8B95AD, primary #6366F1, accent/cyan #22D3EE, warning
// #F59E0B, danger #EF4444, subtitle #FACC15) and add theme-specific accents.
import { styleThemeSchema, type StyleTheme, type StyleThemeInput } from "./schema";

const JAKARTA = "Plus Jakarta Sans";
const MANROPE = "Manrope";
const PLAYFAIR = "Playfair Display";
const ANTON = "Anton";

const RAW: StyleThemeInput[] = [
  {
    name: "bold",
    label: "Bold",
    description: "Standart. Qalin Plus Jakarta 800, sariq highlight, zoom-punch kesimlar, plyonka donasi.",
    fonts: {
      display: { family: JAKARTA, weight: 800, lightWeight: 400, letterSpacing: -0.02, charEm: 0.64 },
      body: { family: MANROPE, weight: 600, charEm: 0.56 },
    },
    colors: {
      bg: "#0B0F19",
      surface: "#131A2A",
      text: "#E6EAF2",
      muted: "#8B95AD",
      primary: "#6366F1",
      accent: "#FACC15",
      highlight: "#FACC15",
      onHighlight: "#0B0F19",
    },
    captionPreset: "karaoke",
    captionStyle: { font: "display", stroke: 6 },
    defaultTextAnim: "WordPop",
    secondaryTextAnim: "Highlighter",
    ctaTextAnim: "BounceIn",
    defaultTransition: "zoomPunch",
    transitionFrames: 10,
    fx: ["grain", "vignette"],
    fxIntensity: { grain: 0.07, vignette: 0.45 },
    background: { kind: "brand", colors: ["#6366F1", "#22D3EE"] },
    headline: { size: 104, hookSize: 124, align: "center", maxLines: 4, stroke: 0 },
    card: { glass: true, radius: 36 },
    kenBurns: "in",
    tempo: 1,
  },
  {
    name: "minimal",
    label: "Minimal",
    description: "Manrope, koʻp boʻsh joy, chapga tekislangan, MaskWipe + fade. Tinch, zamonaviy.",
    fonts: {
      display: { family: MANROPE, weight: 700, lightWeight: 300, letterSpacing: -0.03, charEm: 0.58 },
      body: { family: MANROPE, weight: 500, charEm: 0.56 },
    },
    colors: {
      bg: "#0E1116",
      surface: "#161B22",
      text: "#F2F4F8",
      muted: "#8B95AD",
      primary: "#6366F1",
      accent: "#22D3EE",
      highlight: "#22D3EE",
      onHighlight: "#0E1116",
    },
    captionPreset: "lineByLine",
    captionStyle: { font: "body", stroke: 0, scale: 0.95 },
    defaultTextAnim: "MaskWipe",
    secondaryTextAnim: "TypeWriter",
    ctaTextAnim: "MaskWipe",
    defaultTransition: "fade",
    transitionFrames: 14,
    fx: [],
    background: { kind: "solid", colors: ["#0E1116"] },
    headline: { size: 84, hookSize: 96, align: "left", maxLines: 4, stroke: 0, scrim: 0.35 },
    card: { glass: false, radius: 20 },
    kenBurns: "in",
    tempo: 1.1,
  },
  {
    name: "neon",
    label: "Neon",
    description: "Tungi neon: cyan/magenta, Glitch matn, xromatik aberratsiya, nur, glitch-kesim.",
    fonts: {
      display: { family: JAKARTA, weight: 800, lightWeight: 300, letterSpacing: -0.01, charEm: 0.64 },
      body: { family: MANROPE, weight: 600, charEm: 0.56 },
    },
    colors: {
      bg: "#05010F",
      surface: "#140A2A",
      text: "#F5F3FF",
      muted: "#A78BFA",
      primary: "#E879F9",
      accent: "#22D3EE",
      highlight: "#E879F9",
      onHighlight: "#05010F",
    },
    captionPreset: "bigWord",
    captionStyle: { font: "display", stroke: 0, uppercase: true },
    defaultTextAnim: "Glitch",
    secondaryTextAnim: "Scramble",
    ctaTextAnim: "Outline2Fill",
    defaultTransition: "glitchCut",
    transitionFrames: 8,
    fx: ["chromatic", "glow", "particles", "grain"],
    fxIntensity: { chromatic: 14, glow: 26, grain: 0.06 },
    background: { kind: "mesh", colors: ["#7C3AED88", "#22D3EE55", "#E879F977"] },
    headline: { size: 108, hookSize: 128, align: "center", maxLines: 4, stroke: 0, shadow: "0 0 24px rgba(34,211,238,0.55)" },
    card: { glass: true, radius: 28 },
    kenBurns: "in",
    tempo: 1,
    particlesColor: "#22D3EE",
  },
  {
    name: "editorial",
    label: "Editorial",
    description: "Jurnal uslubi: Playfair Display serif sarlavha, harf-kaskad, marker, slice kesim.",
    fonts: {
      display: { family: PLAYFAIR, weight: 800, lightWeight: 400, letterSpacing: -0.01, charEm: 0.56 },
      body: { family: MANROPE, weight: 600, charEm: 0.56 },
    },
    colors: {
      bg: "#14110F",
      surface: "#1E1A17",
      text: "#F5EFE6",
      muted: "#A89F92",
      primary: "#F59E0B",
      accent: "#F59E0B",
      highlight: "#F59E0B",
      onHighlight: "#14110F",
    },
    captionPreset: "lineByLine",
    captionStyle: { font: "body", stroke: 0 },
    defaultTextAnim: "CharCascade",
    secondaryTextAnim: "Highlighter",
    ctaTextAnim: "SlideMask",
    defaultTransition: "slice",
    transitionFrames: 16,
    fx: ["grain", "vignette"],
    fxIntensity: { grain: 0.09, vignette: 0.5 },
    background: { kind: "solid", colors: ["#14110F"] },
    headline: { size: 110, hookSize: 128, align: "left", maxLines: 4, stroke: 0 },
    card: { glass: false, radius: 8 },
    kenBurns: "left",
    tempo: 1.15,
  },
  {
    name: "corporate",
    label: "Corporate",
    description: "Ishonchli B2B: Manrope, indigo, SlideMask qatorlar, toza shisha kartalar, slide.",
    fonts: {
      display: { family: MANROPE, weight: 800, lightWeight: 400, letterSpacing: -0.02, charEm: 0.6 },
      body: { family: MANROPE, weight: 500, charEm: 0.56 },
    },
    colors: {
      bg: "#0B0F19",
      surface: "#131A2A",
      text: "#E6EAF2",
      muted: "#8B95AD",
      primary: "#6366F1",
      accent: "#818CF8",
      highlight: "#6366F1",
      onHighlight: "#FFFFFF",
    },
    captionPreset: "pillGlass",
    captionStyle: { font: "display", stroke: 0 },
    defaultTextAnim: "SlideMask",
    secondaryTextAnim: "Counter",
    ctaTextAnim: "MaskWipe",
    defaultTransition: "slide",
    transitionFrames: 14,
    fx: ["progressBar"],
    background: { kind: "brand", colors: ["#6366F1", "#22D3EE"] },
    headline: { size: 96, hookSize: 112, align: "center", maxLines: 4, stroke: 0 },
    card: { glass: true, radius: 32 },
    kenBurns: "out",
    tempo: 1,
  },
  {
    name: "hype",
    label: "Hype",
    description: "Energiya: Anton katta harflar, Kinetic ritm, kamera silkinishi, whip-pan, Hormozi subtitr.",
    fonts: {
      display: { family: ANTON, weight: 400, lightWeight: 400, uppercase: true, letterSpacing: 0.01, charEm: 0.46 },
      body: { family: JAKARTA, weight: 800, charEm: 0.64 },
    },
    colors: {
      bg: "#0A0A0A",
      surface: "#171717",
      text: "#FFFFFF",
      muted: "#A3A3A3",
      primary: "#EF4444",
      accent: "#FACC15",
      highlight: "#FACC15",
      onHighlight: "#0A0A0A",
    },
    captionPreset: "boxHighlight",
    captionStyle: { font: "body", stroke: 6, uppercase: true },
    defaultTextAnim: "Kinetic",
    secondaryTextAnim: "Counter",
    ctaTextAnim: "BounceIn",
    defaultTransition: "whipPan",
    transitionFrames: 12,
    fx: ["shake", "grain", "progressBar"],
    fxIntensity: { shake: 14, grain: 0.08 },
    background: { kind: "brand", colors: ["#EF4444", "#FACC15"] },
    headline: { size: 150, hookSize: 170, align: "center", maxLines: 4, stroke: 0, shadow: "0 10px 0 rgba(0,0,0,0.35)" },
    card: { glass: false, radius: 24 },
    kenBurns: "in",
    tempo: 0.85,
  },
  {
    name: "luxury",
    label: "Luxury",
    description: "Premium: toʻq fon, oltin #D4AF37, Playfair, sekin BlurFocus, vinyetka, oltin chang.",
    fonts: {
      display: { family: PLAYFAIR, weight: 600, lightWeight: 400, letterSpacing: 0.01, charEm: 0.55 },
      body: { family: MANROPE, weight: 500, letterSpacing: 0.02, charEm: 0.58 },
    },
    colors: {
      bg: "#07070A",
      surface: "#121017",
      text: "#F4EFE3",
      muted: "#9A8F78",
      primary: "#D4AF37",
      accent: "#D4AF37",
      highlight: "#D4AF37",
      onHighlight: "#07070A",
    },
    captionPreset: "lineByLine",
    captionStyle: { font: "body", stroke: 0, scale: 0.9 },
    defaultTextAnim: "BlurFocus",
    secondaryTextAnim: "CharCascade",
    ctaTextAnim: "BlurFocus",
    defaultTransition: "fade",
    transitionFrames: 20,
    fx: ["vignette", "grain", "particles", "lensFlare"],
    fxIntensity: { vignette: 0.7, grain: 0.06 },
    background: { kind: "mesh", colors: ["#D4AF3730", "#3B2F1A66"] },
    headline: { size: 96, hookSize: 112, align: "center", maxLines: 4, stroke: 0 },
    card: { glass: true, radius: 4 },
    kenBurns: "out",
    tempo: 1.5,
    particlesColor: "#D4AF37",
  },
];

export const THEMES: Record<string, StyleTheme> = Object.fromEntries(
  RAW.map((t) => {
    const parsed = styleThemeSchema.parse(t);
    return [parsed.name, parsed];
  }),
);

export const THEME_NAMES = RAW.map((t) => t.name) as readonly string[];
export const DEFAULT_THEME = "bold";

/** Theme by name (case-insensitive); unknown → "bold". */
export function getTheme(name: string | null | undefined): StyleTheme {
  const key = (name ?? "").trim().toLowerCase();
  return THEMES[key] ?? THEMES[DEFAULT_THEME]!;
}
