// AUTO-GENERATED by `npm run themes:index` from ./*.json — do not edit by hand.
// Add a theme: drop <name>.json here, run `npm run themes:index`, then
// `npm run theme:validate -- src/motion/styles/themes/<name>.json`.
import t_academic from "./academic.json";
import t_bazaarWarm from "./bazaar-warm.json";
import t_beautySoft from "./beauty-soft.json";
import t_bold from "./bold.json";
import t_cafeCream from "./cafe-cream.json";
import t_candy from "./candy.json";
import t_comic from "./comic.json";
import t_corporate from "./corporate.json";
import t_cyber from "./cyber.json";
import t_darkGold from "./dark-gold.json";
import t_earth from "./earth.json";
import t_editorial from "./editorial.json";
import t_estateClean from "./estate-clean.json";
import t_fintechGradient from "./fintech-gradient.json";
import t_fitnessEnergy from "./fitness-energy.json";
import t_foodWarm from "./food-warm.json";
import t_glass from "./glass.json";
import t_glitchDark from "./glitch-dark.json";
import t_handwritten from "./handwritten.json";
import t_hype from "./hype.json";
import t_instagramGradient from "./instagram-gradient.json";
import t_jewel from "./jewel.json";
import t_kids from "./kids.json";
import t_luxury from "./luxury.json";
import t_magazineSerif from "./magazine-serif.json";
import t_medicalClean from "./medical-clean.json";
import t_minimal from "./minimal.json";
import t_monoKinetic from "./mono-kinetic.json";
import t_nature from "./nature.json";
import t_navruz from "./navruz.json";
import t_neon from "./neon.json";
import t_newspaper from "./newspaper.json";
import t_noir from "./noir.json";
import t_pastel from "./pastel.json";
import t_ramadanNight from "./ramadan-night.json";
import t_registanBlue from "./registan-blue.json";
import t_sportEnergy from "./sport-energy.json";
import t_sticker from "./sticker.json";
import t_suzaniRed from "./suzani-red.json";
import t_swiss from "./swiss.json";
import t_synthwave from "./synthwave.json";
import t_techBlue from "./tech-blue.json";
import t_telegramBlue from "./telegram-blue.json";
import t_tiktokDark from "./tiktok-dark.json";
import t_y2k from "./y2k.json";

/** Raw theme JSON (validated by the registry at load time), sorted by file name. */
export const THEME_JSON: readonly unknown[] = [
  t_academic,
  t_bazaarWarm,
  t_beautySoft,
  t_bold,
  t_cafeCream,
  t_candy,
  t_comic,
  t_corporate,
  t_cyber,
  t_darkGold,
  t_earth,
  t_editorial,
  t_estateClean,
  t_fintechGradient,
  t_fitnessEnergy,
  t_foodWarm,
  t_glass,
  t_glitchDark,
  t_handwritten,
  t_hype,
  t_instagramGradient,
  t_jewel,
  t_kids,
  t_luxury,
  t_magazineSerif,
  t_medicalClean,
  t_minimal,
  t_monoKinetic,
  t_nature,
  t_navruz,
  t_neon,
  t_newspaper,
  t_noir,
  t_pastel,
  t_ramadanNight,
  t_registanBlue,
  t_sportEnergy,
  t_sticker,
  t_suzaniRed,
  t_swiss,
  t_synthwave,
  t_techBlue,
  t_telegramBlue,
  t_tiktokDark,
  t_y2k,
];
