// Node-only helpers for the theme JSON folder (npm run themes:index / themes:schema, tests).
import { readdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "zod";
import { styleThemeSchema } from "../motion/styles/schema";

const HERE = path.dirname(fileURLToPath(import.meta.url));
export const APP_DIR = path.resolve(HERE, "../..");
export const THEMES_DIR = path.join(APP_DIR, "src/motion/styles/themes");
export const THEMES_INDEX = path.join(THEMES_DIR, "index.ts");
export const THEME_SCHEMA_FILE = path.join(APP_DIR, "schemas/style-theme.schema.json");

/** *.json file names in the themes folder, sorted. */
export function themeJsonFiles(dir = THEMES_DIR): string[] {
  return readdirSync(dir)
    .filter((f) => f.endsWith(".json"))
    .sort();
}

/** "dark-gold.json" → "darkGold" (valid identifier for the import). */
export const importName = (file: string) =>
  "t_" + file.replace(/\.json$/, "").replace(/[^a-zA-Z0-9]+(.)?/g, (_, c: string | undefined) => (c ? c.toUpperCase() : ""));

/**
 * Source of src/motion/styles/themes/index.ts: explicit JSON imports so the
 * Remotion (webpack) bundle, vitest and tsx all see the same list — no
 * import.meta.glob / require.context.
 */
export function renderThemesIndex(files: string[]): string {
  const lines = [
    "// AUTO-GENERATED by `npm run themes:index` from ./*.json — do not edit by hand.",
    "// Add a theme: drop <name>.json here, run `npm run themes:index`, then",
    "// `npm run theme:validate -- src/motion/styles/themes/<name>.json`.",
    ...files.map((f) => `import ${importName(f)} from "./${f}";`),
    "",
    "/** Raw theme JSON (validated by the registry at load time), sorted by file name. */",
    "export const THEME_JSON: readonly unknown[] = [",
    ...files.map((f) => `  ${importName(f)},`),
    "];",
    "",
  ];
  return lines.join("\n");
}

/** JSON Schema (draft 2020-12) of a theme as authored (defaults optional). */
export function themeJsonSchema(): Record<string, unknown> {
  const schema = z.toJSONSchema(styleThemeSchema, { io: "input", target: "draft-2020-12" }) as Record<string, unknown>;
  return {
    $schema: schema.$schema,
    $id: "https://neta.uz/schemas/style-theme.schema.json",
    title: "Neta StyleTheme",
    description:
      "A Remotion Reels style theme (apps/render/src/motion/styles/schema.ts). Generated by `npm run themes:schema` — do not edit.",
    ...Object.fromEntries(Object.entries(schema).filter(([k]) => k !== "$schema")),
  };
}

export const themeJsonSchemaText = () => JSON.stringify(themeJsonSchema(), null, 2) + "\n";
